version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
